pipeline {
   agent any
       tools {
           maven 'Maven 3.6.3'
           jdk 'jdk8'
       }
       stages {
           stage ('Initialize') {
               steps {
                   sh '''
                       echo "PATH = ${PATH}"
                       echo "M2_HOME = ${M2_HOME}"
                   '''
               }
           }
      /* stage('Build Dataflow Template') {
               steps {
                  sh 'cd /Users/hgo2/IdeaProjects/google-dataflow-pipelines/gcs-to-pubsub/gcs-item-pubsub'
                  sh 'echo "current buld directory"'
                  sh 'pwd'
                  sh '''
                  cd /Users/hgo2/IdeaProjects/google-dataflow-pipelines/gcs-to-pubsub/gcs-item-pubsub
                  ./gcs-to-pubsub-build-template.sh
                  '''
               }
            } */
            stage('Build Dataflow Template') {
            steps {
                                withEnv(['GCLOUD_PATH=/Users/hgo2/Downloads/google-cloud-sdk/bin']){
                              sh '''
                              $GCLOUD_PATH/gcs-to-pubsub-run-job.sh
                              '''
                              }
                           }
                        }
            /* stage('Build Dataflow Template') {
                           steps  {
                              withEnv(['GCLOUD_PATH=/Users/hgo2/Downloads/google-cloud-sdk/bin']){
                              sh '''
                              $GCLOUD_PATH/gcloud dataflow jobs run gerard-gcs-to-pubsub-sample-001 \
                              --region=us-east4  \
                              --gcs-location gs://tst1-integration-3ca6-gerard/pipeline/template/template-gcs-sample-001
                              '''
                              }
                           }
                        } */
      /* stage('Run Dataflow Pipeline Job') {
          steps {
              sh 'cd /Users/hgo2/IdeaProjects/google-dataflow-pipelines/gcs-to-pubsub/gcs-item-pubsub'
              sh '''
              cd /Users/hgo2/IdeaProjects/google-dataflow-pipelines/gcs-to-pubsub/gcs-item-pubsub
              ./gcs-to-pubsub-run-job.sh
              '''
          }
      } */
   }
}