pipeline {
   agent any
       tools {
           maven 'Maven 3.6.3'
           jdk 'jdk8'
       }
       stages {
           stage ('Initialize') {
               steps {
                   sh '''
                       echo "PATH = ${PATH}"
                       echo "M2_HOME = ${M2_HOME}"
                   '''
               }
           }
      stage('Build Dataflow Template') {
               steps {
                  sh 'cd /Users/hgo2/IdeaProjects/google-dataflow-pipelines/gcs-to-pubsub/gcs-item-pubsub'
                  sh 'echo "current buld directory"'
                  sh 'pwd'
                  sh 'cd /Users/hgo2/IdeaProjects/google-dataflow-pipelines/gcs-to-pubsub/gcs-item-pubsub
                  /Users/hgo2/IdeaProjects/google-dataflow-pipelines/gcs-to-pubsub/gcs-item-pubsub/gcs-to-pubsub-build-template.sh' // mvn command to build the template
               }
            }
      stage('Run Dataflow Pipeline Job') {
          steps {
              sh 'cd /Users/hgo2/IdeaProjects/google-dataflow-pipelines/gcs-to-pubsub/gcs-item-pubsub'
              sh './gcs-to-pubsub-run-job.sh'
          }
      }
   }
}